package com.app.towerDefense.models;

import java.awt.Point;
import java.text.SimpleDateFormat;
import java.util.Date;

public class MapModel {
	public String mapSecret;
	public String mapAutoGeneratedDescription;
	Point entryPoint;
	Point exitPoint;
	public boolean isEntryDone;
	public boolean isExitDone;
	public int mapGridSelection[][];
	int mapWidth;
	int mapHeight;

	public MapModel(String mapSecret, String mapAutoGeneratedDescription,
			Point entryPoint, Point exitPoint, boolean isEntryDone,
			boolean isExitDone, int[][] mapGridSelection, int mapWidth,
			int mapHeight) {
		super();
		this.mapSecret = mapSecret;
		this.mapAutoGeneratedDescription= mapAutoGeneratedDescription;
		this.entryPoint=entryPoint;
		this.exitPoint=exitPoint;
		this.isEntryDone = isEntryDone;
		this.isExitDone = isExitDone;
		this.mapGridSelection = mapGridSelection;
		this.mapWidth = mapWidth;
		this.mapHeight = mapHeight;
	}

	public MapModel() {
		// TODO Auto-generated constructor stub
	}

	public String getMapSecret() {
		return mapSecret;
	}

	public void setMapSecret() {
		this.mapSecret = new SimpleDateFormat("yyyyMMddHHmmssSSS").format(new Date())+"_Team5";
	}

	public String getMapAutoGeneratedDescription() {
		return mapAutoGeneratedDescription;
	}

	public void setMapAutoGeneratedDescription(
			String mapAutoGeneratedDescription) {
		this.mapAutoGeneratedDescription = mapAutoGeneratedDescription;
	}

	public boolean isEntryDone() {
		return isEntryDone;
	}

	public void setEntryDone(boolean isEntryDone) {
		this.isEntryDone = isEntryDone;
	}

	public boolean isExitDone() {
		return isExitDone;
	}

	public void setExitDone(boolean isExitDone) {
		this.isExitDone = isExitDone;
	}

	public int[][] getMapGridSelection() {
		return mapGridSelection;
	}

	public void setMapGridSelection(int[][] mapGridSelection) {
		this.mapGridSelection = mapGridSelection;
	}

	public int getMapWidth() {
		return mapWidth;
	}

	public void setMapWidth(int mapWidth) {
		this.mapWidth = mapWidth;
	}

	public int getMapHeight() {
		return mapHeight;
	}

	public void setMapHeight(int mapHeight) {
		this.mapHeight = mapHeight;
	}

	public Point getEntryPoint() {
		return entryPoint;
	}

	public void setEntryPoint(Point entryPoint) {
		this.entryPoint = entryPoint;
	}

	public Point getExitPoint() {
		return exitPoint;
	}

	public void setExitPoint(Point exitPoint) {
		this.exitPoint = exitPoint;
	}

}
